using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;

namespace Editor.LocalizationSyncTool.Services
{
    public static class LocalizationConstantsGenerator
    {
        public const string OUTPUT_PATH =
            "Assets/Immortal Switch/Scripts/Shared/Constants/LocalizationKeys.cs";

        public static int Generate(IEnumerable<string> keys)
        {
            var validKeys = keys
                .Where(key => !string.IsNullOrWhiteSpace(key))
                .Select(key => key.Trim())
                .Distinct(StringComparer.Ordinal)
                .OrderBy(key => key, StringComparer.Ordinal)
                .ToList();

            var source = BuildSource(validKeys);
            var folder = Path.GetDirectoryName(OUTPUT_PATH);

            if (!string.IsNullOrWhiteSpace(folder))
            {
                Directory.CreateDirectory(folder);
            }

            if (!File.Exists(OUTPUT_PATH) ||
                !string.Equals(File.ReadAllText(OUTPUT_PATH), source, StringComparison.Ordinal))
            {
                File.WriteAllText(OUTPUT_PATH, source, new UTF8Encoding(false));
            }

            return validKeys.Count;
        }

        private static string BuildSource(IReadOnlyList<string> keys)
        {
            var builder = new StringBuilder();
            var claimedNames = new Dictionary<string, int>(StringComparer.Ordinal);

            builder.AppendLine("// <auto-generated>");
            builder.AppendLine("// File được tạo tự động bởi Localization Sync. Không chỉnh sửa thủ công.");
            builder.AppendLine("// </auto-generated>");
            builder.AppendLine();
            builder.AppendLine("namespace Immortal_Switch.Scripts.Shared.Constants");
            builder.AppendLine("{");
            builder.AppendLine("    public static class LocalizationKeys");
            builder.AppendLine("    {");

            foreach (var key in keys)
            {
                var baseName = ToConstantName(key);
                claimedNames.TryGetValue(baseName, out var duplicateCount);
                claimedNames[baseName] = duplicateCount + 1;

                var constantName = duplicateCount == 0
                    ? baseName
                    : $"{baseName}_{duplicateCount + 1}";

                builder.Append("        public const string ");
                builder.Append(constantName);
                builder.Append(" = \"");
                builder.Append(EscapeString(key));
                builder.AppendLine("\";");
            }

            builder.AppendLine("    }");
            builder.AppendLine("}");
            return builder.ToString();
        }

        private static string ToConstantName(string key)
        {
            var builder = new StringBuilder();
            var previousWasUnderscore = false;

            foreach (var character in key)
            {
                if (char.IsLetterOrDigit(character))
                {
                    builder.Append(char.ToUpperInvariant(character));
                    previousWasUnderscore = false;
                }
                else if (!previousWasUnderscore &&
                         builder.Length > 0)
                {
                    builder.Append('_');
                    previousWasUnderscore = true;
                }
            }

            var name = builder.ToString().Trim('_');

            if (string.IsNullOrEmpty(name))
            {
                name = "EMPTY_KEY";
            }

            if (char.IsDigit(name[0]))
            {
                name = "_" + name;
            }

            return name;
        }

        private static string EscapeString(string value)
        {
            return value
                .Replace("\\", "\\\\")
                .Replace("\"", "\\\"")
                .Replace("\r", "\\r")
                .Replace("\n", "\\n")
                .Replace("\t", "\\t");
        }
    }
}