// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: proto/service/login/login_service.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Login {

  /// <summary>Holder for reflection information generated from proto/service/login/login_service.proto</summary>
  public static partial class LoginServiceReflection {

    #region Descriptor
    /// <summary>File descriptor for proto/service/login/login_service.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static LoginServiceReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cidwcm90by9zZXJ2aWNlL2xvZ2luL2xvZ2luX3NlcnZpY2UucHJvdG8SBWxv",
            "Z2luGh9wcm90by9zZXJ2aWNlL2xvZ2luL2xvZ2luLnByb3RvMkkKDExvZ2lu",
            "U2VydmljZRI5CgxBdXRoZW50aWNhdGUSEy5sb2dpbi5Mb2dpblJlcXVlc3Qa",
            "FC5sb2dpbi5Mb2dpblJlc3BvbnNlQihaJnByb3RvL2dlbi9nby9wcm90by9z",
            "ZXJ2aWNlL2xvZ2luO2xvZ2luYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Login.LoginReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, null));
    }
    #endregion

  }
}

#endregion Designer generated code
