// <auto-generated>
// File được tạo tự động bởi Localization Sync. Không chỉnh sửa thủ công.
// </auto-generated>

namespace Immortal_Switch.Scripts.Shared.Constants
{
    public static class LocalizationKeys
    {
        public const string UI_LOGIN = "ui_login";
        public const string UI_WHEEL = "ui_wheel";
    }
}
